services:
  redis:
    image: redis:latest
    networks:
      - my-net1
    ports:
      - "6379:6379"
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - my-net1
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - redis
    restart: always
  nginx:
    image: nginx:latest
    networks:
      - my-net1
    restart: always
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
networks:
  my-net1:
    driver: bridge