spring:
    profiles:
        active: dev
        include: secret
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                use_sql_comments: true
            jdbc:
                time_zone: Asia/Seoul
decorator:
    datasource:
        p6spy:
            enable-logging: true
